use crate::interner::StrI;
use crate::parse_arena::ParseArena;
use crate::scout_arena::ScoutArena;

/// All Vale keywords and commonly used identifiers
// TODO: let's bake this into the ParseArena, ScoutArena, etc. and only include ones that are
// actually frequently used by that pass.
pub struct Keywords<'a> {
  pub func: StrI<'a>,
  pub impoort: StrI<'a>,
  pub export: StrI<'a>,
  pub truue: StrI<'a>,
  pub faalse: StrI<'a>,
  pub own: StrI<'a>,
  pub borrow: StrI<'a>,
  pub weak: StrI<'a>,
  pub share: StrI<'a>,
  pub r#where: StrI<'a>,
  pub additive: StrI<'a>,
  pub inl: StrI<'a>,
  pub heap: StrI<'a>,
  pub imm: StrI<'a>,
  pub r#mut: StrI<'a>,
  pub vary: StrI<'a>,
  pub fiinal: StrI<'a>,
  pub exists: StrI<'a>,
  pub resolve: StrI<'a>,
  pub self_: StrI<'a>,
  pub iff: StrI<'a>,
  pub elsse: StrI<'a>,
  pub foreeach: StrI<'a>,
  pub r#in: StrI<'a>,
  pub parallel: StrI<'a>,
  pub r#break: StrI<'a>,
  pub retuurn: StrI<'a>,
  pub whiile: StrI<'a>,
  pub destruct: StrI<'a>,
  pub set: StrI<'a>,
  pub unlet: StrI<'a>,
  pub block: StrI<'a>,
  pub pure: StrI<'a>,
  pub pre: StrI<'a>,
  pub r#unsafe: StrI<'a>,
  pub and: StrI<'a>,
  pub or: StrI<'a>,
  pub r#as: StrI<'a>,
  pub ro: StrI<'a>,
  pub rw: StrI<'a>,
  pub r#virtual: StrI<'a>,
  pub r#impl: StrI<'a>,
  pub int_capitalized: StrI<'a>,
  pub ref_: StrI<'a>,
  pub kind: StrI<'a>,
  pub region: StrI<'a>,
  pub prot: StrI<'a>,
  pub ref_list: StrI<'a>,
  pub ownership: StrI<'a>,
  pub variability: StrI<'a>,
  pub mutability: StrI<'a>,
  pub location: StrI<'a>,
  pub refs: StrI<'a>,
  pub underscore: StrI<'a>,
  pub dot_dot: StrI<'a>,
  pub int: StrI<'a>,
  pub bool: StrI<'a>,
  pub float: StrI<'a>,
  pub __never: StrI<'a>,
  pub str: StrI<'a>,
  pub void: StrI<'a>,
  pub i64: StrI<'a>,
  pub i32: StrI<'a>,
  pub i16: StrI<'a>,
  pub i8: StrI<'a>,
  pub u64: StrI<'a>,
  pub u32: StrI<'a>,
  pub u16: StrI<'a>,
  pub u8: StrI<'a>,
  pub plus: StrI<'a>,
  pub asterisk: StrI<'a>,
  pub slash: StrI<'a>,
  pub minus: StrI<'a>,
  pub spaceship: StrI<'a>,
  pub less_equals: StrI<'a>,
  pub less: StrI<'a>,
  pub greater_equals: StrI<'a>,
  pub greater: StrI<'a>,
  pub triple_equals: StrI<'a>,
  pub double_equals: StrI<'a>,
  pub not_equals: StrI<'a>,
  pub drop: StrI<'a>,
  pub free: StrI<'a>,
  pub linear: StrI<'a>,
  pub not: StrI<'a>,
  pub range: StrI<'a>,
  pub begin: StrI<'a>,
  pub next: StrI<'a>,
  pub is_empty: StrI<'a>,
  pub get: StrI<'a>,
  pub underscores_call: StrI<'a>,
  pub tuple_human_name: Vec<StrI<'a>>,
  pub derive_struct_drop: StrI<'a>,
  pub derive_anonymous_substruct: StrI<'a>,
  pub derive_interface_drop: StrI<'a>,
  pub free_generator: StrI<'a>,
  pub drop_generator: StrI<'a>,
  pub interface_free_generator: StrI<'a>,
  pub vale_static_sized_array_drop_into: StrI<'a>,
  pub vale_runtime_sized_array_push: StrI<'a>,
  pub vale_runtime_sized_array_pop: StrI<'a>,
  pub vale_runtime_sized_array_mut_new: StrI<'a>,
  pub vale_runtime_sized_array_capacity: StrI<'a>,
  pub vale_runtime_sized_array_len: StrI<'a>,
  pub vale_runtime_sized_array_imm_new: StrI<'a>,
  pub vale_runtime_sized_array_free: StrI<'a>,
  pub vale_runtime_sized_array_drop_into: StrI<'a>,
  pub abstract_body: StrI<'a>,
  pub vale_as_subtype: StrI<'a>,
  pub vale_lock_weak: StrI<'a>,
  pub vale_same_instance: StrI<'a>,
  pub struct_constructor_generator: StrI<'a>,
  pub derive_struct_constructor: StrI<'a>,
  pub vale_static_sized_array_free: StrI<'a>,
  pub vale_static_sized_array_len: StrI<'a>,
  pub empty_string: StrI<'a>,
  pub thiss: StrI<'a>,
  pub box_human_name: StrI<'a>,
  pub box_member_name: StrI<'a>,
  pub t: StrI<'a>,
  pub v: StrI<'a>,
  pub drop_p1k: StrI<'a>,
  pub drop_p1: StrI<'a>,
  pub drop_r: StrI<'a>,
  pub drop_struct: StrI<'a>,
  pub drop_struct_template: StrI<'a>,
  pub drop_v: StrI<'a>,
  pub drop_vk: StrI<'a>,
  pub free_p1: StrI<'a>,
  pub free_struct_template: StrI<'a>,
  pub free_struct: StrI<'a>,
  pub free_v: StrI<'a>,
  pub x: StrI<'a>,
  pub d: StrI<'a>,
  pub builtins: StrI<'a>,
  pub arrays: StrI<'a>,
  pub is_interface: StrI<'a>,
  pub implements: StrI<'a>,
  pub is_callable: StrI<'a>,
  pub ref_list_compound_mutability: StrI<'a>,
  pub any: StrI<'a>,
  pub ifunction: StrI<'a>,
  pub m: StrI<'a>,
  pub e: StrI<'a>,
  pub f: StrI<'a>,
  pub array: StrI<'a>,
  pub static_array: StrI<'a>,
  pub list: StrI<'a>,
  pub add: StrI<'a>,
  pub opt: StrI<'a>,
  pub some: StrI<'a>,
  pub none: StrI<'a>,
  pub result: StrI<'a>,
  pub ok: StrI<'a>,
  pub err: StrI<'a>,
  pub functor1: StrI<'a>,
  pub my_module: StrI<'a>,
  pub rust: StrI<'a>,
}

impl<'a> Keywords<'a> {
  pub fn new_for_parse(parse_arena: &ParseArena<'a>) -> Self {
    Keywords {
      func: parse_arena.intern_str("func"),
      impoort: parse_arena.intern_str("import"),
      export: parse_arena.intern_str("export"),
      truue: parse_arena.intern_str("true"),
      faalse: parse_arena.intern_str("false"),
      own: parse_arena.intern_str("own"),
      borrow: parse_arena.intern_str("borrow"),
      weak: parse_arena.intern_str("weak"),
      share: parse_arena.intern_str("share"),
      r#where: parse_arena.intern_str("where"),
      additive: parse_arena.intern_str("additive"),
      inl: parse_arena.intern_str("inl"),
      heap: parse_arena.intern_str("heap"),
      imm: parse_arena.intern_str("imm"),
      r#mut: parse_arena.intern_str("mut"),
      vary: parse_arena.intern_str("vary"),
      fiinal: parse_arena.intern_str("final"),
      exists: parse_arena.intern_str("exists"),
      resolve: parse_arena.intern_str("resolve"),
      self_: parse_arena.intern_str("self"),
      iff: parse_arena.intern_str("if"),
      elsse: parse_arena.intern_str("else"),
      foreeach: parse_arena.intern_str("foreach"),
      r#in: parse_arena.intern_str("in"),
      parallel: parse_arena.intern_str("parallel"),
      r#break: parse_arena.intern_str("break"),
      retuurn: parse_arena.intern_str("return"),
      whiile: parse_arena.intern_str("while"),
      destruct: parse_arena.intern_str("destruct"),
      set: parse_arena.intern_str("set"),
      unlet: parse_arena.intern_str("unlet"),
      block: parse_arena.intern_str("block"),
      pure: parse_arena.intern_str("pure"),
      pre: parse_arena.intern_str("pre"),
      r#unsafe: parse_arena.intern_str("unsafe"),
      and: parse_arena.intern_str("and"),
      or: parse_arena.intern_str("or"),
      r#as: parse_arena.intern_str("as"),
      ro: parse_arena.intern_str("ro"),
      rw: parse_arena.intern_str("rw"),
      r#virtual: parse_arena.intern_str("virtual"),
      r#impl: parse_arena.intern_str("impl"),
      int_capitalized: parse_arena.intern_str("Int"),
      ref_: parse_arena.intern_str("Ref"),
      kind: parse_arena.intern_str("Kind"),
      region: parse_arena.intern_str("Region"),
      prot: parse_arena.intern_str("Prot"),
      ref_list: parse_arena.intern_str("RefList"),
      ownership: parse_arena.intern_str("Ownership"),
      variability: parse_arena.intern_str("Variability"),
      mutability: parse_arena.intern_str("Mutability"),
      location: parse_arena.intern_str("Location"),
      refs: parse_arena.intern_str("Refs"),
      underscore: parse_arena.intern_str("_"),
      dot_dot: parse_arena.intern_str(".."),
      int: parse_arena.intern_str("int"),
      bool: parse_arena.intern_str("bool"),
      float: parse_arena.intern_str("float"),
      __never: parse_arena.intern_str("__Never"),
      str: parse_arena.intern_str("str"),
      void: parse_arena.intern_str("void"),
      i64: parse_arena.intern_str("i64"),
      i32: parse_arena.intern_str("i32"),
      i16: parse_arena.intern_str("i16"),
      i8: parse_arena.intern_str("i8"),
      u64: parse_arena.intern_str("u64"),
      u32: parse_arena.intern_str("u32"),
      u16: parse_arena.intern_str("u16"),
      u8: parse_arena.intern_str("u8"),
      plus: parse_arena.intern_str("+"),
      asterisk: parse_arena.intern_str("*"),
      slash: parse_arena.intern_str("/"),
      minus: parse_arena.intern_str("-"),
      spaceship: parse_arena.intern_str("<=>"),
      less_equals: parse_arena.intern_str("<="),
      less: parse_arena.intern_str("<"),
      greater_equals: parse_arena.intern_str(">="),
      greater: parse_arena.intern_str(">"),
      triple_equals: parse_arena.intern_str("==="),
      double_equals: parse_arena.intern_str("=="),
      not_equals: parse_arena.intern_str("!="),
      drop: parse_arena.intern_str("drop"),
      free: parse_arena.intern_str("free"),
      linear: parse_arena.intern_str("linear"),
      not: parse_arena.intern_str("not"),
      range: parse_arena.intern_str("range"),
      begin: parse_arena.intern_str("begin"),
      next: parse_arena.intern_str("next"),
      is_empty: parse_arena.intern_str("isEmpty"),
      get: parse_arena.intern_str("get"),
      underscores_call: parse_arena.intern_str("__call"),
      tuple_human_name: vec![
        parse_arena.intern_str("Tup0"),
        parse_arena.intern_str("Tup1"),
        parse_arena.intern_str("Tup2"),
        parse_arena.intern_str("Tup3"),
        parse_arena.intern_str("Tup4"),
        parse_arena.intern_str("Tup5"),
        parse_arena.intern_str("Tup6"),
        parse_arena.intern_str("Tup7"),
        parse_arena.intern_str("Tup8"),
        parse_arena.intern_str("Tup9"),
      ],
      derive_struct_drop: parse_arena.intern_str("DeriveStructDrop"),
      derive_anonymous_substruct: parse_arena.intern_str("DeriveAnonymousSubstruct"),
      derive_interface_drop: parse_arena.intern_str("DeriveInterfaceDrop"),
      free_generator: parse_arena.intern_str("freeGenerator"),
      drop_generator: parse_arena.intern_str("dropGenerator"),
      interface_free_generator: parse_arena.intern_str("interfaceFreeGenerator"),
      vale_static_sized_array_drop_into: parse_arena.intern_str("vale_static_sized_array_drop_into"),
      vale_runtime_sized_array_push: parse_arena.intern_str("vale_runtime_sized_array_push"),
      vale_runtime_sized_array_pop: parse_arena.intern_str("vale_runtime_sized_array_pop"),
      vale_runtime_sized_array_mut_new: parse_arena.intern_str("vale_runtime_sized_array_mut_new"),
      vale_runtime_sized_array_capacity: parse_arena.intern_str("vale_runtime_sized_array_capacity"),
      vale_runtime_sized_array_len: parse_arena.intern_str("vale_runtime_sized_array_len"),
      vale_runtime_sized_array_imm_new: parse_arena.intern_str("vale_runtime_sized_array_imm_new"),
      vale_runtime_sized_array_free: parse_arena.intern_str("vale_runtime_sized_array_free"),
      vale_runtime_sized_array_drop_into: parse_arena.intern_str("vale_runtime_sized_array_drop_into"),
      abstract_body: parse_arena.intern_str("abstractBody"),
      vale_as_subtype: parse_arena.intern_str("vale_as_subtype"),
      vale_lock_weak: parse_arena.intern_str("vale_lock_weak"),
      vale_same_instance: parse_arena.intern_str("vale_same_instance"),
      struct_constructor_generator: parse_arena.intern_str("structConstructorGenerator"),
      derive_struct_constructor: parse_arena.intern_str("DeriveStructConstructor"),
      vale_static_sized_array_free: parse_arena.intern_str("vale_static_sized_array_free"),
      vale_static_sized_array_len: parse_arena.intern_str("vale_static_sized_array_len"),
      empty_string: parse_arena.intern_str(""),
      thiss: parse_arena.intern_str("this"),
      box_human_name: parse_arena.intern_str("__Box"),
      box_member_name: parse_arena.intern_str("__boxee"),
      t: parse_arena.intern_str("T"),
      v: parse_arena.intern_str("v"),
      drop_p1k: parse_arena.intern_str("DropP1K"),
      drop_p1: parse_arena.intern_str("DropP1"),
      drop_r: parse_arena.intern_str("DropR"),
      drop_struct: parse_arena.intern_str("DropStruct"),
      drop_struct_template: parse_arena.intern_str("DropStructTemplate"),
      drop_v: parse_arena.intern_str("DropV"),
      drop_vk: parse_arena.intern_str("DropVK"),
      free_p1: parse_arena.intern_str("FreeP1"),
      free_struct_template: parse_arena.intern_str("FreeStructTemplate"),
      free_struct: parse_arena.intern_str("FreeStruct"),
      free_v: parse_arena.intern_str("FreeV"),
      x: parse_arena.intern_str("x"),
      d: parse_arena.intern_str("D"),
      builtins: parse_arena.intern_str("builtins"),
      arrays: parse_arena.intern_str("arrays"),
      is_interface: parse_arena.intern_str("isInterface"),
      implements: parse_arena.intern_str("implements"),
      is_callable: parse_arena.intern_str("isCallable"),
      ref_list_compound_mutability: parse_arena.intern_str("refListCompoundMutability"),
      any: parse_arena.intern_str("any"),
      ifunction: parse_arena.intern_str("IFunction"),
      m: parse_arena.intern_str("M"),
      e: parse_arena.intern_str("E"),
      f: parse_arena.intern_str("F"),
      array: parse_arena.intern_str("Array"),
      static_array: parse_arena.intern_str("StaticArray"),
      list: parse_arena.intern_str("List"),
      add: parse_arena.intern_str("add"),
      opt: parse_arena.intern_str("Opt"),
      some: parse_arena.intern_str("Some"),
      none: parse_arena.intern_str("None"),
      result: parse_arena.intern_str("Result"),
      ok: parse_arena.intern_str("Ok"),
      err: parse_arena.intern_str("Err"),
      functor1: parse_arena.intern_str("Functor1"),
      my_module: parse_arena.intern_str("my_module"),
      rust: parse_arena.intern_str("rust"),
    }
  }

  pub fn new_for_scout(scout_arena: &ScoutArena<'a>) -> Self {
    Keywords {
      func: scout_arena.intern_str("func"),
      impoort: scout_arena.intern_str("import"),
      export: scout_arena.intern_str("export"),
      truue: scout_arena.intern_str("true"),
      faalse: scout_arena.intern_str("false"),
      own: scout_arena.intern_str("own"),
      borrow: scout_arena.intern_str("borrow"),
      weak: scout_arena.intern_str("weak"),
      share: scout_arena.intern_str("share"),
      r#where: scout_arena.intern_str("where"),
      additive: scout_arena.intern_str("additive"),
      inl: scout_arena.intern_str("inl"),
      heap: scout_arena.intern_str("heap"),
      imm: scout_arena.intern_str("imm"),
      r#mut: scout_arena.intern_str("mut"),
      vary: scout_arena.intern_str("vary"),
      fiinal: scout_arena.intern_str("final"),
      exists: scout_arena.intern_str("exists"),
      resolve: scout_arena.intern_str("resolve"),
      self_: scout_arena.intern_str("self"),
      iff: scout_arena.intern_str("if"),
      elsse: scout_arena.intern_str("else"),
      foreeach: scout_arena.intern_str("foreach"),
      r#in: scout_arena.intern_str("in"),
      parallel: scout_arena.intern_str("parallel"),
      r#break: scout_arena.intern_str("break"),
      retuurn: scout_arena.intern_str("return"),
      whiile: scout_arena.intern_str("while"),
      destruct: scout_arena.intern_str("destruct"),
      set: scout_arena.intern_str("set"),
      unlet: scout_arena.intern_str("unlet"),
      block: scout_arena.intern_str("block"),
      pure: scout_arena.intern_str("pure"),
      pre: scout_arena.intern_str("pre"),
      r#unsafe: scout_arena.intern_str("unsafe"),
      and: scout_arena.intern_str("and"),
      or: scout_arena.intern_str("or"),
      r#as: scout_arena.intern_str("as"),
      ro: scout_arena.intern_str("ro"),
      rw: scout_arena.intern_str("rw"),
      r#virtual: scout_arena.intern_str("virtual"),
      r#impl: scout_arena.intern_str("impl"),
      int_capitalized: scout_arena.intern_str("Int"),
      ref_: scout_arena.intern_str("Ref"),
      kind: scout_arena.intern_str("Kind"),
      region: scout_arena.intern_str("Region"),
      prot: scout_arena.intern_str("Prot"),
      ref_list: scout_arena.intern_str("RefList"),
      ownership: scout_arena.intern_str("Ownership"),
      variability: scout_arena.intern_str("Variability"),
      mutability: scout_arena.intern_str("Mutability"),
      location: scout_arena.intern_str("Location"),
      refs: scout_arena.intern_str("Refs"),
      underscore: scout_arena.intern_str("_"),
      dot_dot: scout_arena.intern_str(".."),
      int: scout_arena.intern_str("int"),
      bool: scout_arena.intern_str("bool"),
      float: scout_arena.intern_str("float"),
      __never: scout_arena.intern_str("__Never"),
      str: scout_arena.intern_str("str"),
      void: scout_arena.intern_str("void"),
      i64: scout_arena.intern_str("i64"),
      i32: scout_arena.intern_str("i32"),
      i16: scout_arena.intern_str("i16"),
      i8: scout_arena.intern_str("i8"),
      u64: scout_arena.intern_str("u64"),
      u32: scout_arena.intern_str("u32"),
      u16: scout_arena.intern_str("u16"),
      u8: scout_arena.intern_str("u8"),
      plus: scout_arena.intern_str("+"),
      asterisk: scout_arena.intern_str("*"),
      slash: scout_arena.intern_str("/"),
      minus: scout_arena.intern_str("-"),
      spaceship: scout_arena.intern_str("<=>"),
      less_equals: scout_arena.intern_str("<="),
      less: scout_arena.intern_str("<"),
      greater_equals: scout_arena.intern_str(">="),
      greater: scout_arena.intern_str(">"),
      triple_equals: scout_arena.intern_str("==="),
      double_equals: scout_arena.intern_str("=="),
      not_equals: scout_arena.intern_str("!="),
      drop: scout_arena.intern_str("drop"),
      free: scout_arena.intern_str("free"),
      linear: scout_arena.intern_str("linear"),
      not: scout_arena.intern_str("not"),
      range: scout_arena.intern_str("range"),
      begin: scout_arena.intern_str("begin"),
      next: scout_arena.intern_str("next"),
      is_empty: scout_arena.intern_str("isEmpty"),
      get: scout_arena.intern_str("get"),
      underscores_call: scout_arena.intern_str("__call"),
      tuple_human_name: vec![
        scout_arena.intern_str("Tup0"),
        scout_arena.intern_str("Tup1"),
        scout_arena.intern_str("Tup2"),
        scout_arena.intern_str("Tup3"),
        scout_arena.intern_str("Tup4"),
        scout_arena.intern_str("Tup5"),
        scout_arena.intern_str("Tup6"),
        scout_arena.intern_str("Tup7"),
        scout_arena.intern_str("Tup8"),
        scout_arena.intern_str("Tup9"),
      ],
      derive_struct_drop: scout_arena.intern_str("DeriveStructDrop"),
      derive_anonymous_substruct: scout_arena.intern_str("DeriveAnonymousSubstruct"),
      derive_interface_drop: scout_arena.intern_str("DeriveInterfaceDrop"),
      free_generator: scout_arena.intern_str("freeGenerator"),
      drop_generator: scout_arena.intern_str("dropGenerator"),
      interface_free_generator: scout_arena.intern_str("interfaceFreeGenerator"),
      vale_static_sized_array_drop_into: scout_arena.intern_str("vale_static_sized_array_drop_into"),
      vale_runtime_sized_array_push: scout_arena.intern_str("vale_runtime_sized_array_push"),
      vale_runtime_sized_array_pop: scout_arena.intern_str("vale_runtime_sized_array_pop"),
      vale_runtime_sized_array_mut_new: scout_arena.intern_str("vale_runtime_sized_array_mut_new"),
      vale_runtime_sized_array_capacity: scout_arena.intern_str("vale_runtime_sized_array_capacity"),
      vale_runtime_sized_array_len: scout_arena.intern_str("vale_runtime_sized_array_len"),
      vale_runtime_sized_array_imm_new: scout_arena.intern_str("vale_runtime_sized_array_imm_new"),
      vale_runtime_sized_array_free: scout_arena.intern_str("vale_runtime_sized_array_free"),
      vale_runtime_sized_array_drop_into: scout_arena.intern_str("vale_runtime_sized_array_drop_into"),
      abstract_body: scout_arena.intern_str("abstractBody"),
      vale_as_subtype: scout_arena.intern_str("vale_as_subtype"),
      vale_lock_weak: scout_arena.intern_str("vale_lock_weak"),
      vale_same_instance: scout_arena.intern_str("vale_same_instance"),
      struct_constructor_generator: scout_arena.intern_str("structConstructorGenerator"),
      derive_struct_constructor: scout_arena.intern_str("DeriveStructConstructor"),
      vale_static_sized_array_free: scout_arena.intern_str("vale_static_sized_array_free"),
      vale_static_sized_array_len: scout_arena.intern_str("vale_static_sized_array_len"),
      empty_string: scout_arena.intern_str(""),
      thiss: scout_arena.intern_str("this"),
      box_human_name: scout_arena.intern_str("__Box"),
      box_member_name: scout_arena.intern_str("__boxee"),
      t: scout_arena.intern_str("T"),
      v: scout_arena.intern_str("v"),
      drop_p1k: scout_arena.intern_str("DropP1K"),
      drop_p1: scout_arena.intern_str("DropP1"),
      drop_r: scout_arena.intern_str("DropR"),
      drop_struct: scout_arena.intern_str("DropStruct"),
      drop_struct_template: scout_arena.intern_str("DropStructTemplate"),
      drop_v: scout_arena.intern_str("DropV"),
      drop_vk: scout_arena.intern_str("DropVK"),
      free_p1: scout_arena.intern_str("FreeP1"),
      free_struct_template: scout_arena.intern_str("FreeStructTemplate"),
      free_struct: scout_arena.intern_str("FreeStruct"),
      free_v: scout_arena.intern_str("FreeV"),
      x: scout_arena.intern_str("x"),
      d: scout_arena.intern_str("D"),
      builtins: scout_arena.intern_str("builtins"),
      arrays: scout_arena.intern_str("arrays"),
      is_interface: scout_arena.intern_str("isInterface"),
      implements: scout_arena.intern_str("implements"),
      is_callable: scout_arena.intern_str("isCallable"),
      ref_list_compound_mutability: scout_arena.intern_str("refListCompoundMutability"),
      any: scout_arena.intern_str("any"),
      ifunction: scout_arena.intern_str("IFunction"),
      m: scout_arena.intern_str("M"),
      e: scout_arena.intern_str("E"),
      f: scout_arena.intern_str("F"),
      array: scout_arena.intern_str("Array"),
      static_array: scout_arena.intern_str("StaticArray"),
      list: scout_arena.intern_str("List"),
      add: scout_arena.intern_str("add"),
      opt: scout_arena.intern_str("Opt"),
      some: scout_arena.intern_str("Some"),
      none: scout_arena.intern_str("None"),
      result: scout_arena.intern_str("Result"),
      ok: scout_arena.intern_str("Ok"),
      err: scout_arena.intern_str("Err"),
      functor1: scout_arena.intern_str("Functor1"),
      my_module: scout_arena.intern_str("my_module"),
      rust: scout_arena.intern_str("rust"),
    }
  }
}
