[package]
name = "BenchmarkRL"
version = "0.1.0"
authors = ["Verdagon <verdagon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generational-arena = "0.2"
printf = "0.1.0"