mod compiler_test_compilation;
mod humanize_helper;
mod compiler_tests;
pub mod traverse;
mod compiler_generics_tests;
mod compiler_lambda_tests;
mod compiler_mutate_tests;
mod compiler_ownership_tests;
mod compiler_project_tests;
mod compiler_solver_tests;
mod compiler_virtual_tests;
mod after_regions_tests;
mod after_regions_error_tests;
mod compiler_humanizer_tests;
mod in_progress_tests;
mod todo_tests;
