# Do_not_edit_directly._See_readme_section_editing_github_workflows

name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  CARGO_TERM_COLOR: always
jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: install prereqs
        run: cmd /c '.\install-compiler-prereqs-windows.bat C:\llvm-install-minimum C:\ValeCompiler-0.1.3.4-Win'
      - name: run vcvars and build-compiler-windows.bat
        run: cmd /c '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && .\build-compiler-windows.bat C:\llvm-install-minimum C:\ValeCompiler-0.1.3.4-Win'
  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install prereqs
        run: ./install-compiler-prereqs-linux.sh ~/ValeLLVM ~/ValeCompiler-0.1.3.3-Ubuntu
      - name: build compiler
        run: ./build-compiler-linux.sh ~/ValeLLVM/clang+llvm-11.1.0-x86_64-linux-gnu-ubuntu-20.10 ~/ValeCompiler-0.1.3.3-Ubuntu
  build_and_test_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: stub
        run: echo stubbed out for now
