name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - name: install prereqs
        run: cmd /c '.\scripts\windows\install-compiler-prereqs.bat C:\llvm-project-llvmorg-13.0.1 C:\BootstrappingValeCompiler'
      - name: run vcvars and build-compiler-windows.bat
        run: cmd /c '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && .\scripts\windows\build-compiler.bat C:\LLVM13\llvm-project-llvmorg-13.0.1 C:\BootstrappingValeCompiler --test=all scripts\VERSION'
      - uses: actions/upload-artifact@v2
        with:
          name: Vale-Windows-0.zip
          path: .\release-windows\Vale-Windows-0.zip

  build_and_test_ubuntu:
    runs-on: ubuntu-20.04
    steps: 
      - uses: actions/checkout@v2
      - name: install prereqs
        run: ./scripts/ubuntu/install-compiler-prereqs.sh ~/LLVMForVale ~/BootstrappingValeCompiler
      - name: build compiler 
        run: ./scripts/ubuntu/build-compiler.sh ~/LLVMForVale/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04 ~/BootstrappingValeCompiler --test=all ./scripts/VERSION
      - uses: actions/upload-artifact@v2
        with:
          name: Vale-Ubuntu-0.zip
          path: ./release-ubuntu/Vale-Ubuntu-0.zip

  build_and_test_mac:
    runs-on: macos-12
    steps: 
      - uses: actions/checkout@v2
      - name: install prereqs
        run: ./scripts/mac/install-compiler-prereqs.sh ~/BootstrappingValeCompiler
      - name: build compiler
        run: source ~/.zshrc && ./scripts/mac/build-compiler.sh ~/BootstrappingValeCompiler --test=all ./scripts/VERSION
      - uses: actions/upload-artifact@v2
        with:
          name: Vale-Mac-0.zip
          path: ./release-mac/Vale-Mac-0.zip

