name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test_windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: install prereqs
        run: cmd /c '.\install-compiler-prereqs-windows.bat C:\LLVM13 C:\BootstrappingValeCompiler'
      - name: run vcvars and build-compiler-windows.bat
        run: cmd /c '"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat" && .\build-compiler-windows.bat C:\LLVM13\llvm-project-llvmorg-13.0.1 C:\BootstrappingValeCompiler'
      - uses: actions/upload-artifact@v2
        with:
          name: ValeCompiler-0-Win.zip
          path: .\release-windows\ValeCompiler.zip

  build_and_test_ubuntu:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: install prereqs
        run: ./install-compiler-prereqs-linux.sh ~/LLVMForVale ~/BootstrappingValeCompiler
      - name: build compiler 
        run: ./build-compiler-linux.sh ~/LLVMForVale/clang+llvm-13.0.1-x86_64-linux-gnu-ubuntu-18.04 ~/BootstrappingValeCompiler
      - uses: actions/upload-artifact@v2
        with:
          name: ValeCompiler-0-Ubuntu.zip
          path: ./release-unix/ValeCompiler.zip

  build_and_test_mac:
    runs-on: macos-latest
    steps: 
      - uses: actions/checkout@v2
      - name: install prereqs
        run: ./install-compiler-prereqs-mac.sh ~/ValeCompiler-0.1.3.3-Mac
      - name: build compiler
        run: source ~/.zshrc && ./build-compiler-mac.sh ~/ValeCompiler-0.1.3.3-Mac ~/stdlib
      - uses: actions/upload-artifact@v2
        with:
          name: ValeCompiler-0-Mac.zip
          path: ./release-unix/ValeCompiler.zip

